version: '3.9'

services:
  app:
    build: .
    container_name: app
    ports:
      - 7000:7500
    volumes:
      - .:/usr/home/app
    depends_on:
      - db
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootpass
      - POSTGRES_DB=somedb_dev
    ports:
      - 5432:15432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql
